server:
  port: 8084

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: trazabilidad

  data:
    mongodb:
      uri: mongodb://localhost:27017/${TRACEABILITY_DB_DATABASE}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka