server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${USER_DB_DATABASE}
    username: postgres
    password: ${USER_DB_PASSWORD}
  application:
    name: usuarios

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
