server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios
    username: postgres
    password: 1010
  application:
    name: usuarios

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
