server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${PLAZOLETA_DB_DATABASE}
    username: postgres
    password: ${PLAZOLETA_DB_PASSWORD}
  application:
    name: plazoleta

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
