spring:
  application:
    name: api-gateway
server:
  port: 443
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring.cloud.gateway:
  discovery:
    locator:
      enabled: true
      lower-case-service-id: true
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "localhost:4200"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE
        allowedHeaders:
          - "*"
        allowCredentials: true

  cloud:
    gateway:
      routes:
        - id: plazoleta
          uri: http://plazoleta
          predicates:
            - Path=/plazoleta/**
          filters:
            - StripPrefix=1
            - RequestHeaderToRequestUri=Cookie
